#!/system/bin/sh
# execute any postinstall script then kill it
if [ -e /data/firstboot.sh ];
then
    echo "--- Executing firstboot.sh";
    /system/bin/sh /data/firstboot.sh;
    rm -f /data/firstboot.sh;
fi;

if [ -e /data/firstboot_to_run.sh ];
then
    echo "--- Making execute firstboot.sh";
    mv /data/firstboot_to_run.sh /data/firstboot.sh
fi;

if [ -e /data/samdroidtools.sh ];
then
    echo "--- Executing samdroidtools.sh";
    /system/bin/sh /data/samdroidtools.sh;
fi;

