
TARGET_CPU_ABI := armeabi
USE_CAMERA_STUB := true
TARGET_BOOTLOADER_BOARD_NAME := GT-I5700
TARGET_NO_BOOTLOADER := true
TARGET_NO_KERNEL := true
TARGET_NO_RADIOIMAGE := true
TARGET_BOARD_PLATFORM := s3c6410
BOARD_USES_GENERIC_AUDIO := true
BOARD_USES_ALSA_AUDIO := true
